default_install_hook_types:
- pre-commit
- commit-msg
repos:

# Pre-commit hygiene hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files

- repo: https://github.com/PyCQA/isort
  rev: 7.0.0
  hooks:
    - id: isort
      args: [
          "--profile", "black",
          "--line-length", "120",
          "--py", "39",
          "--atomic",
          "--trailing-comma",
          "--multi-line", "3",
          "--lines-after-imports", "2",
          "--force-alphabetical-sort-within-sections"
      ]

# mypy type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
    - id: mypy
      additional_dependencies: [
        types-requests,
        types-python-dateutil
      ]
      args: [
        "--ignore-missing-imports",
        "--disallow-untyped-defs",
        "--pretty"
      ]

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
  hooks:
    - id: conventional-pre-commit
      args: ["--strict"]
      stages:
      - commit-msg

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
    - id: ruff
      args: [
        "--fix",
        "--per-file-ignores", '__init__.py:F401'
      ]
      types_or:
      - python
      - pyi
    - id: ruff-format
      types_or:
      - python
      - pyi

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      args: ["--skip=*/regexes.py,*/pii-regex-detections/*"]
