default_install_hook_types:
  - pre-commit
  - commit-msg

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Black formatter
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
    - id: black
      args: ["--line-length=120"]

  # isort for import sorting (synced with VS Code args)
- repo: https://github.com/PyCQA/isort
  rev: 7.0.0
  hooks:
    - id: isort
      args: [
        "--profile", "black",
        "--line-length", "120",
        "--py", "39",
        "--atomic",
        "--trailing-comma",
        "--multi-line", "3",
        "--lines-after-imports", "2",
        "--force-alphabetical-sort-within-sections"
      ]

# flake8 linting
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear        # catches common Python bugs
        - flake8-comprehensions # checks list/dict/set comprehensions
        - flake8-pyproject      # allow config in pyproject.toml
      args: [
        "--max-line-length=120",
        "--extend-ignore=E203,W503"   # compatible with Black
      ]

# mypy type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
    - id: mypy
      additional_dependencies: [
        types-requests,   # example: add stubs for requests
        types-python-dateutil
      ]
      args: [
        "--ignore-missing-imports",
        "--disallow-untyped-defs",
        "--pretty"
      ]

# Pre-commit hygiene hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: ["--strict"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.6  # Use the latest version or pin to your preferred one
  hooks:
    - id: ruff
      args: [--fix]  # Optional: auto-fix issues
      types_or: [python, pyi]  # Exclude Jupyter notebooks
      # files: "^src/"
    - id: ruff-format
      types_or: [python, pyi]
      # files: "^src/"
